name: ecep
description: Plateforme d'apprentissage en ligne
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  sqflite: ^2.2.8
  path_provider: ^2.0.11
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.1
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  file_picker: ^5.2.5
  flutter_local_notifications: ^16.3.2 
  path: ^1.8.2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/